### ISSUE TITLE
Custom model with XGen for downstream task

### ISSUE THREAD

**Issue by EmileGustave** [XgenTimeSeries/xgen-timeseries#6]
Hello, thank you for this powerful framework, I would like to use it for multi tasks in downstream like classification and regression at once! In XGen we have access to the regression, could you please explain how I could add a custom model for such tasks in downstream class! Thank you again! 
Best,

**Comment by oublalkhalid** [comment]
I'm delighted that you find the framework robust and are interested in utilizing it for multi-task downstream activities, including classification and regression. To incorporate custom models for these tasks within downstream classes, follow these steps:

1. **Model Placement**:
   - First, place your custom models in the `/models/` directory.

2. **Update `active_models`**:
   - Next, add the filename of your custom model to the `active_models` class. This ensures that your models are recognized and accessible. You can find a detailed example of this process in the framework's readme.

I hope this guidance helps you successfully address your requirements! I eagerly await your feedback and any additional questions to assist with resolving any issues you may encounter.

**Comment by EmileGustave** [comment]
Thank you for your clarity, finally I add my down stream model for classification to XGen!
